x = input('Digite algo: ')
print('O tipo primitivo de x é', type(x))
print('{} é alpha numerico {}'.format(x, x.isalnum()))
print('{} é um numero {}'.format(x, x.isnumeric()))
print('{} é uma palavra {}'.format(x, x.isalpha()))
print('{} é uma palavra maiuscula {}'.format(x, x.isupper()))
print('{} é uma palavra minuscula {}'.format(x, x.islower()))
print('{} é um decimal {}'.format(x, x.isdecimal()))
print('{} é capitalizado {}'.format(x, x.istitle()))
print('{} só tem espaço {}'.format(x, x.isidentifier()))
